name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://repo.harmonyos.com/npm'
    
    - name: Install dependencies
      run: |
        npm install -g @ohos/hvigor
        npm install -g @ohos/hvigor-ohos-plugin
    
    - name: Build
      run: hvigor --mode module --product default --target default
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: entry/build/default/outputs/*.hap