name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm config set registry https://repo.harmonyos.com/npm
        npm install @ohos/hvigor --save
        npm install @ohos/hvigor-ohos-plugin --save
    
    - name: Build
      run: node node_modules/@ohos/hvigor/bin/hvigor.js --mode module assembleHap
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: entry/build/default/outputs/*.hap